import type { FormDefinition } from "./forms-store";

export const SAMPLE_FORM_IDS = {
  siteVisit: "form-site-visit",
  brochure: "form-brochure",
  floorPlan: "form-floor-plan",
} as const;

function base(partial: FormDefinition): FormDefinition {
  return partial;
}

export function sampleBuilderForms(configurations: string[] = []): FormDefinition[] {
  const now = "2026-09-07T00:00:00.000Z";
  const choices = configurations.length > 0 ? configurations : [];
  return [
    base({
      id: SAMPLE_FORM_IDS.siteVisit,
      createdAt: now,
      updatedAt: now,
      name: "Site visit enquiry",
      description: "Form Builder sample — used on hero, page form, and project widget.",
      embed: { id: "emb-site-visit", allowExternal: true },
      pdf: { enabled: false, url: "", filename: "brochure.pdf", autoDownload: true },
      thankYouPage: {
        enabled: true,
        heading: "Thank you",
        description: "Our team will call you shortly.",
        text: "",
        image: "",
        icon: "CheckCircle2",
        buttons: [],
        html: "",
        successMessage: "Thanks — our team will call you shortly.",
        showPdfConfirmation: false,
        typography: { fontFamily: "Inter", fontSize: 16, fontWeight: 400, lineHeight: 1.6, textColor: "#111827" },
        colors: { bg: "#ffffff", text: "#111827", accent: "#6D5DFC" },
        background: "#ffffff",
        spacing: { padding: 32, margin: 0, gap: 16 },
        alignment: "center",
      },
      notifyEmail: "",
      whatsapp: "",
      thankYou: "Thanks — our team will call you shortly.",
      multiStep: false,
      templateId: "custom",
      saveToCrm: true,
      sendEmail: false,
      sendWhatsapp: false,
      redirectThankYou: false,
      submitLabel: "Book site visit",
      deliverableUrl: "",
      deliverableLabel: "",
      fields: [
        { id: "sv-name", type: "text", label: "Full name", placeholder: "Your name", required: true },
        { id: "sv-phone", type: "phone", label: "Phone number", placeholder: "Phone", required: true },
        { id: "sv-email", type: "email", label: "Email address", placeholder: "you@email.com", required: false },
        { id: "sv-interest", type: "select", label: "Interested in", placeholder: "Choose a configuration", required: false, options: choices },
        { id: "sv-when", type: "select", label: "Preferred visit", placeholder: "Choose a slot", required: false, options: ["Weekday", "Weekend"] },
      ],
      successAction: "message",
      successUrl: "",
      successTitle: "",
      errorMessage: "Please fill in the required fields.",
      openPopupId: "",
      customActions: [],
    }),
    base({
      id: SAMPLE_FORM_IDS.brochure,
      createdAt: now,
      updatedAt: now,
      name: "Brochure download",
      description: "Form Builder sample — brochure and gated downloads.",
      embed: { id: "emb-brochure", allowExternal: true },
      pdf: { enabled: true, url: "", filename: "brochure.pdf", autoDownload: true },
      thankYouPage: {
        enabled: true,
        heading: "Brochure unlocked",
        description: "Your download will start shortly.",
        text: "",
        image: "",
        icon: "CheckCircle2",
        buttons: [],
        html: "",
        successMessage: "Verified — your brochure is downloading.",
        showPdfConfirmation: true,
        typography: { fontFamily: "Inter", fontSize: 16, fontWeight: 400, lineHeight: 1.6, textColor: "#111827" },
        colors: { bg: "#ffffff", text: "#111827", accent: "#6D5DFC" },
        background: "#ffffff",
        spacing: { padding: 32, margin: 0, gap: 16 },
        alignment: "center",
      },
      notifyEmail: "",
      whatsapp: "",
      thankYou: "Verified — your brochure is downloading.",
      multiStep: false,
      templateId: "custom",
      saveToCrm: true,
      sendEmail: false,
      sendWhatsapp: false,
      redirectThankYou: false,
      submitLabel: "Submit & download",
      deliverableUrl: "",
      deliverableLabel: "Brochure",
      fields: [
        { id: "br-name", type: "text", label: "Full name", placeholder: "Your name", required: true },
        { id: "br-phone", type: "phone", label: "Phone number", placeholder: "Phone", required: true },
        { id: "br-email", type: "email", label: "Email address", placeholder: "you@email.com", required: true },
      ],
      successAction: "message",
      successUrl: "",
      successTitle: "",
      errorMessage: "Please fill in the required fields.",
      openPopupId: "",
      customActions: [],
    }),
    base({
      id: SAMPLE_FORM_IDS.floorPlan,
      createdAt: now,
      updatedAt: now,
      name: "Floor plan unlock",
      description: "Form Builder sample — unlock floor plans after enquiry.",
      embed: { id: "emb-floor-plan", allowExternal: true },
      pdf: { enabled: false, url: "", filename: "brochure.pdf", autoDownload: false },
      thankYouPage: {
        enabled: true,
        heading: "Floor plans unlocked",
        description: "You can now view the selected plan.",
        text: "",
        image: "",
        icon: "CheckCircle2",
        buttons: [],
        html: "",
        successMessage: "Unlocked — view the floor plan.",
        showPdfConfirmation: false,
        typography: { fontFamily: "Inter", fontSize: 16, fontWeight: 400, lineHeight: 1.6, textColor: "#111827" },
        colors: { bg: "#ffffff", text: "#111827", accent: "#6D5DFC" },
        background: "#ffffff",
        spacing: { padding: 32, margin: 0, gap: 16 },
        alignment: "center",
      },
      notifyEmail: "",
      whatsapp: "",
      thankYou: "Unlocked — view the floor plan.",
      multiStep: false,
      templateId: "custom",
      saveToCrm: true,
      sendEmail: false,
      sendWhatsapp: false,
      redirectThankYou: false,
      submitLabel: "View floor plan",
      deliverableUrl: "",
      deliverableLabel: "",
      fields: [
        { id: "fp-name", type: "text", label: "Full name", placeholder: "Your name", required: true },
        { id: "fp-phone", type: "phone", label: "Phone number", placeholder: "Phone", required: true },
        { id: "fp-email", type: "email", label: "Email address", placeholder: "you@email.com", required: false },
      ],
      successAction: "message",
      successUrl: "",
      successTitle: "",
      errorMessage: "Please fill in the required fields.",
      openPopupId: "",
      customActions: [],
    }),
  ];
}
