-- Reconcile live database with schema.prisma. Captures drift that accumulated
-- between the model file and earlier hand-written/raw SQL migrations:
--   * email_configs / email_logs id was created as gen_random_uuid()/no default
--     while schema models id as @default(uuid()) (client-side) and updated_at
--     as @updatedAt (client-side) — drop the DB-level defaults to match.
--   * platform_configs.id @default("platform") is a static value → DB default.
--   * org_types.updated_at @updatedAt has no DB default.
--   * org_types_pkey restored (was dropped by an earlier reconciliation).
--   * organisations.profile removed from the model.
--   * platform_configs.hostinger_api_token removed from the model.
--   * landing_pages.project_id no longer part of the LandingPage model.
--   * leads.configurations / tags dropped their DB defaults.
--   * email_configs.org_id unique index created by model (@unique), mirrored.

-- Generated by: prisma migrate diff --from-url <live db> --to-schema-datamodel prisma/schema.prisma --script

-- DropIndex
DROP INDEX "templates"."landing_pages_project_id_idx";

-- AlterTable
ALTER TABLE "audit"."email_logs" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "identity"."email_configs" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "identity"."org_types" ALTER COLUMN "updated_at" DROP DEFAULT,
ADD CONSTRAINT "org_types_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "identity"."organisations" DROP COLUMN "profile";

-- AlterTable
ALTER TABLE "identity"."platform_configs" DROP COLUMN "hostinger_api_token",
ALTER COLUMN "id" SET DEFAULT 'platform',
ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "templates"."landing_pages" DROP COLUMN "project_id";

-- AlterTable
ALTER TABLE "templates"."leads" ALTER COLUMN "configurations" DROP DEFAULT,
ALTER COLUMN "tags" DROP DEFAULT;

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "email_configs_org_id_key" ON "identity"."email_configs"("org_id");