# -------------------------
# 1️⃣ Builder Stage
# -------------------------
FROM node:20-alpine AS builder

WORKDIR /app
RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY prisma ./prisma
RUN pnpm prisma generate

COPY . .
RUN pnpm build

# -------------------------
# 2️⃣ Production Stage
# -------------------------
FROM node:20-alpine

WORKDIR /app
RUN corepack enable

ARG GIT_SHA=unknown
ENV GIT_SHA=$GIT_SHA

# Copy node_modules from builder
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules

# Copy built files
COPY --from=builder /app/dist ./dist

# Copy prisma folder
COPY --from=builder /app/prisma ./prisma

# Copy Firebase config
COPY --from=builder /app/config ./config

COPY docker-entrypoint.sh ./docker-entrypoint.sh
RUN chmod +x docker-entrypoint.sh

EXPOSE 3000

CMD ["./docker-entrypoint.sh"]

