// Real icon rendering for the landing-page builder + renderer.
// Icons are stored as string names (lucide icon names) in page documents.
// Legacy documents may still contain emoji / raw glyphs — those fall back
// to plain text rendering so nothing breaks.

import type { CSSProperties, ReactNode } from "react";
import {
  ArrowDown,
  ArrowRight,
  ArrowUp,
  Award,
  Baby,
  BadgeCheck,
  Banknote,
  BarChart3,
  Bath,
  Bed,
  Box,
  Building2,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  Check,
  CheckCheck,
  CheckCircle2,
  Clapperboard,
  ClipboardEdit,
  ClipboardList,
  Clock,
  Code,
  Columns2,
  Contact,
  Copy,
  CreditCard,
  Crown,
  Diamond,
  Download,
  Dumbbell,
  Eye,
  FileText,
  Flame,
  FolderOpen,
  FormInput,
  Gift,
  GraduationCap,
  Grid3x3,
  Grip,
  GripVertical,
  HardHat,
  Heading,
  HeartHandshake,
  HelpCircle,
  Hexagon,
  History,
  Home,
  Hourglass,
  Image,
  Images,
  IndianRupee,
  KeyRound,
  Landmark,
  LayoutTemplate,
  Layers,
  Lightbulb,
  Lock,
  LockKeyhole,
  Mail,
  Map,
  MapPin,
  Medal,
  MessageCircle,
  Minus,
  Monitor,
  MousePointerClick,
  MoveVertical,
  PanelBottom,
  PanelTop,
  PartyPopper,
  PenLine,
  Pencil,
  Phone,
  PhoneCall,
  PiggyBank,
  Plane,
  Play,
  Plus,
  Puzzle,
  Quote,
  Redo2,
  Rocket,
  Rows3,
  Ruler,
  Save,
  School,
  ShieldCheck,
  Smartphone,
  Smile,
  Sofa,
  Sparkles,
  Square,
  Star,
  Stethoscope,
  Tablet,
  Tag,
  Tags,
  Target,
  Terminal,
  Trash2,
  TrainFront,
  TreePine,
  Trees,
  Trophy,
  Type,
  Undo2,
  Upload,
  UserRound,
  UsersRound,
  Volleyball,
  Wallet,
  Waves,
  X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  home: Home,
  star: Star,
  sparkles: Sparkles,
  "hard-hat": HardHat,
  waves: Waves,
  dumbbell: Dumbbell,
  "key-round": KeyRound,
  key: KeyRound,
  "map-pin": MapPin,
  location: MapPin,
  "building-2": Building2,
  building: Building2,
  wallet: Wallet,
  volleyball: Volleyball,
  tennis: Volleyball,
  trees: Trees,
  "tree-pine": TreePine,
  sofa: Sofa,
  car: Car,
  "shield-check": ShieldCheck,
  security: ShieldCheck,
  baby: Baby,
  "train-front": TrainFront,
  metro: TrainFront,
  plane: Plane,
  school: School,
  "graduation-cap": GraduationCap,
  stethoscope: Stethoscope,
  hospital: Stethoscope,
  smile: Smile,
  trophy: Trophy,
  calendar: Calendar,
  "calendar-days": CalendarDays,
  lightbulb: Lightbulb,
  idea: Lightbulb,
  flame: Flame,
  phone: Phone,
  "phone-call": PhoneCall,
  mail: Mail,
  email: Mail,
  clock: Clock,
  download: Download,
  upload: Upload,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  plus: Plus,
  x: X,
  copy: Copy,
  check: Check,
  "check-circle": CheckCircle2,
  "check-check": CheckCheck,
  "help-circle": HelpCircle,
  question: HelpCircle,
  quote: Quote,
  target: Target,
  rocket: Rocket,
  gift: Gift,
  type: Type,
  heading: Heading,
  "mouse-pointer-click": MousePointerClick,
  minus: Minus,
  "move-vertical": MoveVertical,
  grip: Grip,
  "grip-vertical": GripVertical,
  code: Code,
  terminal: Terminal,
  clapperboard: Clapperboard,
  "clipboard-list": ClipboardList,
  "clipboard-edit": ClipboardEdit,
  form: FormInput,
  "form-input": FormInput,
  "message-circle": MessageCircle,
  whatsapp: MessageCircle,
  hourglass: Hourglass,
  images: Images,
  image: Image,
  camera: Camera,
  play: Play,
  "bar-chart-3": BarChart3,
  ruler: Ruler,
  bed: Bed,
  bath: Bath,
  "indian-rupee": IndianRupee,
  rupee: IndianRupee,
  banknote: Banknote,
  creditcard: CreditCard,
  tag: Tag,
  tags: Tags,
  "piggy-bank": PiggyBank,
  user: UserRound,
  "user-round": UserRound,
  users: UsersRound,
  "users-round": UsersRound,
  lock: Lock,
  "lock-keyhole": LockKeyhole,
  crown: Crown,
  award: Award,
  medal: Medal,
  "party-popper": PartyPopper,
  "badge-check": BadgeCheck,
  "heart-handshake": HeartHandshake,
  pencil: Pencil,
  "pen-line": PenLine,
  "layout-template": LayoutTemplate,
  layers: Layers,
  box: Box,
  "grid-3x3": Grid3x3,
  grid: Grid3x3,
  "columns-2": Columns2,
  "rows-3": Rows3,
  square: Square,
  diamond: Diamond,
  hexagon: Hexagon,
  contact: Contact,
  map: Map,
  landmark: Landmark,
  puzzle: Puzzle,
  history: History,
  "trash-2": Trash2,
  monitor: Monitor,
  tablet: Tablet,
  smartphone: Smartphone,
  "folder-open": FolderOpen,
  "panel-top": PanelTop,
  "panel-bottom": PanelBottom,
  "file-text": FileText,
  save: Save,
  eye: Eye,
  "undo-2": Undo2,
  "redo-2": Redo2,
};

export const ICON_OPTIONS: { value: string; label: string }[] = Object.keys(
  ICON_MAP,
).map((name) => ({ value: name, label: name }));

export function isKnownIcon(name: unknown): name is string {
  return typeof name === "string" && name.length > 0 && name in ICON_MAP;
}

export function Icon({
  name,
  size = 40,
  color,
  strokeWidth = 2,
  style,
}: {
  name: unknown;
  size?: number | string;
  color?: string;
  strokeWidth?: number;
  style?: CSSProperties;
}): ReactNode {
  const IconCmp = typeof name === "string" ? ICON_MAP[name] : undefined;
  if (!IconCmp) {
    return (
      <span style={{ fontSize: size, color, lineHeight: 1, ...style }}>
        {typeof name === "string" && name.length > 0 ? name : "•"}
      </span>
    );
  }
  return (
    <IconCmp
      size={size}
      color={color}
      strokeWidth={strokeWidth}
      style={{ flexShrink: 0, ...style }}
    />
  );
}
